data:
  amount_col: "Betrag"
  issue_col: "Belegdatum"
  due_col: "Faellig"
  additional_date_columns:
    - "Datum"
  numeric_columns: []
  categorical_columns:
    - "Land"
    - "BUK"
    - "Debitor"
    - "Ampel"
    - "negativ"
  text_columns:
    - "DEB_Name"
    - "Massnahme_2025"
    - "Hinweise"
  target_col: "Massnahme_2025"
  null_like:
    - ""
    - " "
    - "-"
    - "_"
    - "n/a"
    - "na"
    - "nan"
    - "None"

  flag_columns:
    - "negativ"
    - "Ruckmeldung_erhalten"

preprocessing:
  tfidf_max_features: 4000
  tfidf_min_df: 2
  tfidf_ngram_max: 2

model:
  type: "random_forest"
  random_forest:
    n_estimators: 300
    class_weight: "balanced"
    random_state: 42
    n_jobs: -1

evaluation:
  validation_size: 0.25
  top_k: 3
  review_share: 0.2
  cost_review: 50.0
  cost_miss: 250.0

pattern_analysis:
  date_features:
    - weekday
    - is_weekend
    - month
    - quarter
  numeric_features:
    is_round: [0, 2]
    quantiles: [0.25, 0.5, 0.75]
    zero_check: true
    extreme_percentile: 0.98
  categorical_features:
    top_k: 10
    include_other: true
  text_features:
    length_buckets: [50, 200]
    non_empty: true
  min_lift: 1.15
  min_samples: 20
  max_p_value: 0.05
  max_feature_values: 30
  top_n: 40
